#!/bin/bash
# This script compiles the css dependencies for the website and listens for
# changes to the file. It will recompile the css file whenever the less file
# changes. We have this script because this is not a node app and does not need
# the added complexity of a Gruntfile.
# Author: Alvin Lin (alvin.lin@stuypulse.com)
# Dependencies: inotify-tools (sudo apt-get)

while inotifywait -r *.less; do
    lessc styles.less --clean-css="-s0 --advanced" > styles.css
done
