/**
 * @author omgimanerd
 */

const PLAYER_CONSTANTS = {
  BULLET_COOLDOWN: 800,
  BULLETS_PER_SHOT: 1,
  DEFAULT_HITBOX_SIZE: 20,
  MAX_HEALTH: 10,
  ROCKET_COOLDOWN: 1500,
  SHIELD_HITBOX_SIZE: 38,
  SPEED: 0.4,
  TURN_RATE: 0.005,
}

export default PLAYER_CONSTANTS
