/**
 * @author omgimanerd
 */

enum SOUNDS {
  BULLET_SHOT = 'BULLET_SHOT',
  EXPLOSION = 'EXPLOSION',
  GUN_POWERUP = 'GUN_POWERUP',
  HEALTH_PACK = 'HEALTH_PACK',
  LASER_CHARGE = 'LASER_CHARGE',
  LASER_SHOT = 'LASER_SHOT',
  ROCKET_SHOT = 'ROCKET_SHOT',
  SHIELD_POWERUP = 'SHIELD_POWERUP',
}

export default SOUNDS
