/**
 * @author omgimanerd
 */

enum SPRITES {
  BULLET = 'BULLET',
  EXPLOSION = 'EXPLOSION',
  HEALTH_PACK_POWERUP = 'HEALTH_PACK_POWERUP',
  LASER_POWERUP = 'LASER_POWERUP',
  OTHER_TANK = 'OTHER_TANK',
  OTHER_TURRET = 'OTHER_TURRET',
  RAPIDFIRE_POWERUP = 'RAPIDFIRE_POWERUP',
  ROCKET = 'ROCKET',
  ROCKET_POWERUP = 'ROCKET_POWERUP',
  SELF_TANK = 'SELF_TANK',
  SELF_TURRET = 'SELF_TURRET',
  SHIELD = 'SHIELD',
  SHIELD_POWERUP = 'SHIELD_POWERUP',
  SHOTGUN_POWERUP = 'SHOTGUN_POWERUP',
  SPEEDBOOST_POWERUP = 'SPEEDBOOST_POWERUP',
  TILE = 'TILE',
}

export default SPRITES
