/**
 * This class stores global constants between the client and server.
 * @author alvin.lin.dev@gmail.com (Alvin Lin)
 */

module.exports = {
  WORLD_MIN: 0,
  WORLD_MAX: 5000,
  WORLD_PADDING: 30,

  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT: 600,

  MAX_MAP_POWERUPS: 10,

  PLAYER_TURN_RATE: 0.005,
  PLAYER_DEFAULT_SPEED: 300,
  PLAYER_SHOT_COOLDOWN: 800,
  PLAYER_DEFAULT_HITBOX_SIZE: 20,
  PLAYER_SHIELD_HITBOX_SIZE: 45,
  PLAYER_MAX_HEALTH: 10,

  BULLET_DEFAULT_DAMAGE: 1,
  BULLET_VELOCITY_MAGNITUDE: 850,
  BULLET_MAX_TRAVEL_DISTANCE: 1000 * 1000,
  BULLET_HITBOX_SIZE: 10
}
